In [3]:
import pandas as pd

In [4]:
highlighted_block = pd.read_csv("student_performance_dataset.csv")

In [5]:
print(highlighted_block)

         Student_Name  Study_Hours  Attendance_Pct  Class_Participation  \
0          Liam Smith           15              95                    8
1      Olivia Johnson            5              70                    4
2       Noah Williams           12              88                    7
3          Emma Brown           18              98                    9
4        Oliver Jones            7              80                    5
5          Ava Garcia            3              60                    3
6       Elijah Miller           14              90                    8
7     Charlotte Davis           20             100                   10
8   William Rodriguez            9              85                    6
9     Sophia Martinez           11              82                    7
10    James Hernandez           16              92                    8
11       Amelia Lopez            6              75                    5
12  Benjamin Gonzalez           13              89                    7
13    Isabella Wilson           19              97                    9
14     Lucas Anderson            8              78                    6
15         Mia Thomas            4              65                    4
16       Henry Taylor           15              91                    8
17       Evelyn Moore           21             100                   10
18  Alexander Jackson           10              84                    6
19      Harper Martin           12              86                    7
20          Mason Lee           14              93                    9
21       Camila Perez            5              68                    3
22   Michael Thompson           11              87                    7
23       Gianna White           17              96                    9
24       Ethan Harris            8              82                    5
25    Abigail Sanchez            2              55                    2
26       Daniel Clark           13              92                    8
27       Luna Ramirez           22              99                   10
28        Jacob Lewis            9              80                    6
29      Ella Robinson           12              85                    7
30       Logan Walker           16              94                    8
31    Elizabeth Young            6              72                    4
32      Jackson Allen           14              88                    8
33         Sofia King           18              95                    9
34        Levi Wright            7              79                    5
35        Avery Scott            3              62                    3
36   Sebastian Torres           15              90                    8
37    Scarlett Nguyen           20              98                   10
38          Jack Hill           10              83                    6
39       Emily Flores           11              84                    7
40         Owen Green           15              96                    9
41         Aria Adams            4              66                    4
42    Theodore Nelson           13              91                    7
43     Penelope Baker           19              99                   10
44           Sam Hall            8              81                    5
45       Chloe Rivera            2              58                    2
46    Joseph Campbell           14              89                    8
47     Layla Mitchell           21             100                   10
48        John Carter            9              82                    6
49     Milani Roberts           12              87                    7

    Previous_Score  Final_Score
0               85           90
1               60           55
2               78           82
3               92           96
4               65           68
5               50           45
6               80           85
7               95           99
8               70           72
9               75           78
10              88           91
11              58           60
12              81           84
13              94           95
14              66           67
15              52           50
16              83           87
17              97          100
18              72           74
19              76           79
20              86           89
21              55           52
22              79           80
23              90           93
24              68           70
25              45           40
26              82           86
27              96           98
28              71           73
29              74           77
30              87           90
31              61           58
32              79           83
33              91           94
34              64           66
35              48           46
36              84           88
37              95           97
38              73           75
39              77           76
40              89           92
41              54           53
42              80           82
43              93           96
44              67           69
45              47           42
46              81           85
47              98           99
48              69           71
49              76           79

In [11]:
# view data
highlighted_block.head()

,Student_Name,Study_Hours,Attendance_Pct,Class_Participation,Previous_Score,Final_Score
0,Liam Smith,15,95,8,85,90
1,Olivia Johnson,5,70,4,60,55
2,Noah Williams,12,88,7,78,82
3,Emma Brown,18,98,9,92,96
4,Oliver Jones,7,80,5,65,68

In [6]:
student_name = highlighted_block["Student_Name"]
study_hours = highlighted_block["Study_Hours"]
attendance_pct = highlighted_block["Attendance_Pct"]
class_participation = highlighted_block["Class_Participation"]
previous_score = highlighted_block["Previous_Score"]
final_score = highlighted_block["Final_Score"]

In [9]:
print(highlighted_block)

         Student_Name  Study_Hours  Attendance_Pct  Class_Participation  \
0          Liam Smith           15              95                    8
1      Olivia Johnson            5              70                    4
2       Noah Williams           12              88                    7
3          Emma Brown           18              98                    9
4        Oliver Jones            7              80                    5
5          Ava Garcia            3              60                    3
6       Elijah Miller           14              90                    8
7     Charlotte Davis           20             100                   10
8   William Rodriguez            9              85                    6
9     Sophia Martinez           11              82                    7
10    James Hernandez           16              92                    8
11       Amelia Lopez            6              75                    5
12  Benjamin Gonzalez           13              89                    7
13    Isabella Wilson           19              97                    9
14     Lucas Anderson            8              78                    6
15         Mia Thomas            4              65                    4
16       Henry Taylor           15              91                    8
17       Evelyn Moore           21             100                   10
18  Alexander Jackson           10              84                    6
19      Harper Martin           12              86                    7
20          Mason Lee           14              93                    9
21       Camila Perez            5              68                    3
22   Michael Thompson           11              87                    7
23       Gianna White           17              96                    9
24       Ethan Harris            8              82                    5
25    Abigail Sanchez            2              55                    2
26       Daniel Clark           13              92                    8
27       Luna Ramirez           22              99                   10
28        Jacob Lewis            9              80                    6
29      Ella Robinson           12              85                    7
30       Logan Walker           16              94                    8
31    Elizabeth Young            6              72                    4
32      Jackson Allen           14              88                    8
33         Sofia King           18              95                    9
34        Levi Wright            7              79                    5
35        Avery Scott            3              62                    3
36   Sebastian Torres           15              90                    8
37    Scarlett Nguyen           20              98                   10
38          Jack Hill           10              83                    6
39       Emily Flores           11              84                    7
40         Owen Green           15              96                    9
41         Aria Adams            4              66                    4
42    Theodore Nelson           13              91                    7
43     Penelope Baker           19              99                   10
44           Sam Hall            8              81                    5
45       Chloe Rivera            2              58                    2
46    Joseph Campbell           14              89                    8
47     Layla Mitchell           21             100                   10
48        John Carter            9              82                    6
49     Milani Roberts           12              87                    7

    Previous_Score  Final_Score
0               85           90
1               60           55
2               78           82
3               92           96
4               65           68
5               50           45
6               80           85
7               95           99
8               70           72
9               75           78
10              88           91
11              58           60
12              81           84
13              94           95
14              66           67
15              52           50
16              83           87
17              97          100
18              72           74
19              76           79
20              86           89
21              55           52
22              79           80
23              90           93
24              68           70
25              45           40
26              82           86
27              96           98
28              71           73
29              74           77
30              87           90
31              61           58
32              79           83
33              91           94
34              64           66
35              48           46
36              84           88
37              95           97
38              73           75
39              77           76
40              89           92
41              54           53
42              80           82
43              93           96
44              67           69
45              47           42
46              81           85
47              98           99
48              69           71
49              76           79

In [10]:
print(final_score)

0      90
1      55
2      82
3      96
4      68
5      45
6      85
7      99
8      72
9      78
10     91
11     60
12     84
13     95
14     67
15     50
16     87
17    100
18     74
19     79
20     89
21     52
22     80
23     93
24     70
25     40
26     86
27     98
28     73
29     77
30     90
31     58
32     83
33     94
34     66
35     46
36     88
37     97
38     75
39     76
40     92
41     53
42     82
43     96
44     69
45     42
46     85
47     99
48     71
49     79
Name: Final_Score, dtype: int64

In [16]:
#summary statistics
highlighted_block.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Student_Name         50 non-null     object
 1   Study_Hours          50 non-null     int64
 2   Attendance_Pct       50 non-null     int64
 3   Class_Participation  50 non-null     int64
 4   Previous_Score       50 non-null     int64
 5   Final_Score          50 non-null     int64
dtypes: int64(5), object(1)
memory usage: 2.5+ KB

In [18]:
highlighted_block.describe()

,Study_Hours,Attendance_Pct,Class_Participation,Previous_Score,Final_Score
count,50.000000,50.000000,50.000000,50.000000,50.000000
mean,11.760000,84.720000,6.780000,75.520000,77.120000
std,5.468127,11.885577,2.234151,14.577366,16.637357
min,2.000000,55.000000,2.000000,45.000000,40.000000
25%,8.000000,80.000000,5.000000,66.250000,68.250000
50%,12.000000,87.000000,7.000000,77.500000,79.500000
75%,15.000000,93.750000,8.000000,86.750000,90.000000
max,22.000000,100.000000,10.000000,98.000000,100.000000

In [24]:
#students who studied more than 15hrs
highlighted_block[highlighted_block["Study_Hours"] > 15]

,Student_Name,Study_Hours,Attendance_Pct,Class_Participation,Previous_Score,Final_Score
3,Emma Brown,18,98,9,92,96
7,Charlotte Davis,20,100,10,95,99
10,James Hernandez,16,92,8,88,91
13,Isabella Wilson,19,97,9,94,95
17,Evelyn Moore,21,100,10,97,100
23,Gianna White,17,96,9,90,93
27,Luna Ramirez,22,99,10,96,98
30,Logan Walker,16,94,8,87,90
33,Sofia King,18,95,9,91,94
37,Scarlett Nguyen,20,98,10,95,97
43,Penelope Baker,19,99,10,93,96
47,Layla Mitchell,21,100,10,98,99

In [35]:
#sorting
sorted_highlighted_block = highlighted_block.sort_values(by ='Final_Score', ascending=False)
print(sorted_highlighted_block)

         Student_Name  Study_Hours  Attendance_Pct  Class_Participation  \
17       Evelyn Moore           21             100                   10
47     Layla Mitchell           21             100                   10
7     Charlotte Davis           20             100                   10
27       Luna Ramirez           22              99                   10
37    Scarlett Nguyen           20              98                   10
3          Emma Brown           18              98                    9
43     Penelope Baker           19              99                   10
13    Isabella Wilson           19              97                    9
33         Sofia King           18              95                    9
23       Gianna White           17              96                    9
40         Owen Green           15              96                    9
10    James Hernandez           16              92                    8
30       Logan Walker           16              94                    8
0          Liam Smith           15              95                    8
20          Mason Lee           14              93                    9
36   Sebastian Torres           15              90                    8
16       Henry Taylor           15              91                    8
26       Daniel Clark           13              92                    8
6       Elijah Miller           14              90                    8
46    Joseph Campbell           14              89                    8
12  Benjamin Gonzalez           13              89                    7
32      Jackson Allen           14              88                    8
42    Theodore Nelson           13              91                    7
2       Noah Williams           12              88                    7
22   Michael Thompson           11              87                    7
49     Milani Roberts           12              87                    7
19      Harper Martin           12              86                    7
9     Sophia Martinez           11              82                    7
29      Ella Robinson           12              85                    7
39       Emily Flores           11              84                    7
38          Jack Hill           10              83                    6
18  Alexander Jackson           10              84                    6
28        Jacob Lewis            9              80                    6
8   William Rodriguez            9              85                    6
48        John Carter            9              82                    6
24       Ethan Harris            8              82                    5
44           Sam Hall            8              81                    5
4        Oliver Jones            7              80                    5
14     Lucas Anderson            8              78                    6
34        Levi Wright            7              79                    5
11       Amelia Lopez            6              75                    5
31    Elizabeth Young            6              72                    4
1      Olivia Johnson            5              70                    4
41         Aria Adams            4              66                    4
21       Camila Perez            5              68                    3
15         Mia Thomas            4              65                    4
35        Avery Scott            3              62                    3
5          Ava Garcia            3              60                    3
45       Chloe Rivera            2              58                    2
25    Abigail Sanchez            2              55                    2

    Previous_Score  Final_Score
17              97          100
47              98           99
7               95           99
27              96           98
37              95           97
3               92           96
43              93           96
13              94           95
33              91           94
23              90           93
40              89           92
10              88           91
30              87           90
0               85           90
20              86           89
36              84           88
16              83           87
26              82           86
6               80           85
46              81           85
12              81           84
32              79           83
42              80           82
2               78           82
22              79           80
49              76           79
19              76           79
9               75           78
29              74           77
39              77           76
38              73           75
18              72           74
28              71           73
8               70           72
48              69           71
24              68           70
44              67           69
4               65           68
14              66           67
34              64           66
11              58           60
31              61           58
1               60           55
41              54           53
21              55           52
15              52           50
35              48           46
5               50           45
45              47           42
25              45           40